const int size1 = 3;
const int size2 = 4;
void init_rand(int mas[size1][size2]);
void init_keyboard(int mas[size1][size2]);
void init_from_num(int mas[size1][size2]);
void show(int mas[size1][size2]);
void min_mass(int mas[size1][size2]);
void max_mass(int mas[size1][size2]);
void bubble_sort(int mas[size1][size2]);
void sum_mass(int mas[size1][size2]);
void razn_mass(int mas[size1][size2]);
void min_str(int mas[size1][size2]);
void max_str(int mas[size1][size2]);
